### ISSUE TITLE
There needs to be a public spreadsheet listing what /tg/ PRs aren't ported and why

### ISSUE THREAD

**Issue by Victor239** [Whitesands13/Whitesands#206]
Columns in the spreadsheet:
1. PR title
2. PR URL
3. Reason why it isn't ported 

Would really help with:
- Maintaining the codebase
- Focusing the server on what the unique selling points are
- Explaining to tg refugees who want to quickly know what the differences are

**Comment by MarkSuckerberg** [comment]
Nobody has shown interest, and we're to a point that the list would be too big to be of any use IMO.
