### ISSUE TITLE
Pen Uplink not given at roundstart properly

### ISSUE THREAD

**Issue by Maldaris** [Whitesands13/Whitesands#455]
## Round ID:

Round ID: [1603](https://scrubby.melonmesa.com/round/1603)

## Testmerges:
#420: 'TGUI Upgrades and new UI features' by MarkSuckerberg at commit e43396f635
#413: 'Box Facelift part 2 - EVA' by SynnGraffkin at commit 2a6dee5846
#403: 'Hardhat Helmet Sprites' by Quantum-M at commit 3a129575c9
#445: 're:TerraGov' by triplezeta at commit 90f27ff9cb

## Reproduction:

Select Pen uplink for Traitor. Pen will be in PDA, code will be added to memory, however pen will not respond to uplink turn degrees. Admins had to re-add the uplink manually.

**Comment by untrius** [comment]
I have been unable to reproduce this one.  I tried once on my test server when it was first reported, and the pen uplink worked.  I also had a pen uplink on the all-antag round after the bluespace cataclysm event, and the pen uplink worked.

**Comment by Jack7D1** [comment]
This issue was fixed in the past @MarkSuckerberg

**Comment by Maldaris** [comment]
Been fixed on master for awhile, closing.
