### ISSUE TITLE
[FEATURE] Configurable Channel Tokens

### ISSUE THREAD

**Issue by Maldaris** [Whitesands13/Whitesands#507]
## Name of feature:
Configurable Channel Tokens

### Related Pull Request on other codebase:
N/A (To my knowledge)

### Additional Info:
As @untrius mentioned in #506 we're running into issues with colliding `say` prefixes that are either not failing fast & loud, or could potentially be overridden by upstream changes. 

The proposed solution would be a central registry for channel tokens, configurable by server config, and possibly then further modifiable by player configuration locally to the client. Either way, the goal would be to centralize the token definitions for channel prefixes and have a set of error handling cases that report either on server start or on `say` calls that there is an ambiguous token prefix defining the channel. This would add potentially a few seconds at most to roundstart initialization (instead of having compile-time `#DEFINE` macros) but it would give greater visibility in testing, and have the basis to deliver more customization options to the players.

**Comment by untrius** [comment]
For reference, here are the mode keys as I know them to be:

a - xenos
b - binary
c - command
d - deadmin
e - engineering
f - (unused)
g - changeling
h - department
i - intercom
j - borers (waspstation only)
k - slimes
l - left hand
m - medical
n - science
o - ai private
p - admin
q - (unused)
r - right hand
s - security
t - syndicate
u - supply
v - service
w - (unused)
x - vocalcords
y - centcomm
z - (unused)
0 though 9 - (unused)

**Comment by untrius** [comment]
Being the only one left who's looked at this I can say, this is really complicated and I'm not sure if it's worth the effort.  It would be far simpler to just maintain the token list document.
