### ISSUE TITLE
[BUG] Aliens cannot corrode r-walls, creating a role that is born to die in xeno eggs.

### ISSUE THREAD

**Issue by Epsilos** [Whitesands13/Whitesands#524]
## Reproduction: 
Reinforced walls do not take damage from corrosive acid from praetorians/queens. The outer grille remains intact. What this means for players is that, when a scientist decides they want to have a captive xeno, that xeno has literally no chance to experience the game outside of the box, even without the presence of the BZ canister to lull them into glitched permanent sleep. I was on the receiving end of this, but I don't want to bwoink anyone who does this knowingly, so please fix this fast.

**Comment by Superyodeler** [comment]
I think that xenos being unable to escape the containment chamber in xenobio without the shield losing power is intentional. Not an admin, but I feel it would kinda be self antag for a scientist to create an antag designed as a round ender without a decent way to keep them completely secure.

**Comment by dinnerwoerror** [comment]
back in my day on the presage, literally every single time the xeno egg spawned, there was some guy who wanted captive xenos, and literally every single time we had captive xenos, there was some fuck who turned off the shields or there was some fuck who sabotaged the APC or there was some fuck who straight up just opened the cage door for them, basically every single time there's captive xenos, they either are exterminated or breach containment before science fulfills their fetish and cargo fulfills their bounty
