### ISSUE TITLE
what if we added a slide construction kit

### ISSUE THREAD

**Issue by WindowsErrors** [Whitesands13/Whitesands#535]
## Name of feature:
like the slide from the McDonald's play place

### Related Pull Request on other codebase:
we could do it ourselves and use some stupid conveyer belt code or something

### Additional Info:
bro it's a slide it would be really nice

**Comment by triplezeta** [comment]
i support this

**Comment by dee-dubya** [comment]
wyci

and wyci, speedmerge it
