### ISSUE TITLE
[BUG] getting cloned makes you colorblind for a period of time

### ISSUE THREAD

**Issue by triplezeta** [Whitesands13/Whitesands#561]
## Round ID:

i forgot

## Reproduction:

1. die
2. get cloned
3. be unable to see color

**Comment by dee-dubya** [comment]
not permanent, wore off for me after like a minute I'd say?

not sure what is causing post-cloon colorblindness though

**Comment by triplezeta** [comment]
oh

**Comment by SynnGraffkin** [comment]
It was perm for me last night during the event.
