### ISSUE TITLE
[BUG] jake op appeared on a 25pop round

### ISSUE THREAD

**Issue by triplezeta** [Whitesands13/Whitesands#683]
## Round ID:

2250

**Comment by Maldaris** [comment]
Okay not to be a dick, but you literally posted this while the round was in progress.

**Comment by theboy6545** [comment]
a who?

**Comment by Maldaris** [comment]
Fix for this is to make sure the check accurately compares to `src.intern_pop_max`
![image](https://user-images.githubusercontent.com/1953773/104081862-9009be00-51ff-11eb-8c08-a4c3cade36d1.png)
