### ISSUE TITLE
Whiteship is stuck in the past and thus I can't land

### ISSUE THREAD

**Issue by ADepressedPyroshark** [Whitesands13/Whitesands#685]
Issue reported from  Round ID: 2253 (White Sands - RP)

Reporting client version: 513.1536

You can't land in a different area in the white ship, the landing/docking computer shows the z-level it was originally on, even if you moved away else where.
Steps to reproduce:
1. Get whiteship
2. fly to a different energy signature
3. Try to land somewhere
4. suffer in hyperspace

Note: I did try and land in the old z-level, it tells me "Please use a docking computer to specify dock location.Error finding available docking port!"
So marg pls fix

**Comment by MarkSuckerberg** [comment]
maybe use a docking computer like the nice computer asked

**Comment by TheNeoGamer42** [comment]
I have had this issue too, the docking computer only shows the first Zlevel you try to put a docking spot on, unless you rebuild the console with a screwdriver, resetting it

**Comment by MarkSuckerberg** [comment]
there's the real bug

**Comment by TheNeoGamer42** [comment]
Theres also a rather strange bug that I was dealing with yesterday that fixed itself once when I ahelped about it, and then never fixed itself again once the bug happened again, should I just put it here, or make a new report?

**Comment by MarkSuckerberg** [comment]
nah, I know what that was and have fixed it (to my knowledge), so unless it happens again you don't need to

**Comment by MarkSuckerberg** [comment]
fixed
