### ISSUE TITLE
Attempting to undock says an error about ~0% fuel remaining, even though its at 99%

### ISSUE THREAD

**Issue by TheNeoGamer42** [Whitesands13/Whitesands#693]
Issue reported from  Round ID: 2274 (White Sands - RP)

Reporting client version: 513.1532
pretty sure this is supposed to be a warning for if your a donk and try to take off without space gas but its probably not working since it says you have no spacegas when you have spacegas
![image](https://user-images.githubusercontent.com/58159167/104382767-9344c880-54e3-11eb-980f-c760b13bb79c.png)

**Comment by MarkSuckerberg** [comment]
Fixed
