### ISSUE TITLE
[BUG] IPC name broke

### ISSUE THREAD

**Issue by guardsmanfallout** [Whitesands13/Whitesands#714]
## Round ID:
2342

## Testmerges:
#601 #704, neither are likely to cause this.

## Reproduction:
As an IPC, have a name including numbers. After the round ends and you're in the lobby for a new round, look at your name. The numbers have disappeared for no good or discernable reason. This can additionally sometimes happen via customizing your IPC a bit.

**Comment by WindowsErrors** [comment]
i think it's because there's some tg-era code that forces people to have a normal name written in the latin alphabet so that you can't have your name be X-AE-81 12 or техника дүкөнү адам or متجر لاجهزة الكمبيوتر

**Comment by AsciiSquid** [comment]
Yeah IPC's and some other species are set to use a more lenient version. However there's likely a check somewhere that isn't taking that into account.
