### ISSUE TITLE
[BUG] Dwarves dont get nutrition from drinking

### ISSUE THREAD

**Issue by TheRealScarHomie** [Whitesands13/Whitesands#762]
## Round ID:
Every Round

## Reproduction:

It is stated that drinking booze replenishes dwarves nutrition, this is not the case and leads with your character starving every single round (also dwarves still throw up from booze so they always lose nutrition). To test this, be a dwarf, drink, starve. Also every other food type is gross to them so cant even like, eat something else because not only wont it do anything but I also think it makes you throw up and lose more nutrition.

**Comment by scarwolff** [comment]
potential fix in #769
