### ISSUE TITLE
[BUG] Movement Speed Issues Megathread

### ISSUE THREAD

**Issue by Maldaris** [Whitesands13/Whitesands#763]
Please post the Round ID, Test Merges, and Reproduction Methods you've encountered issues with "sticky" movement speed modifiers, or other behaviors that don't match expectations. Please be as descriptive as possible.

**Comment by triplezeta** [comment]
bug: magboots are quirky and you remain slow when you turn them off
reproduction: turn on magboots, turn off again, walk

**Comment by Jack7D1** [comment]
Broken bones: When you break your leg but let it heal naturally the speed modifier is not always removed.
I cannot recall the round ID i encountered this issue however LordGrievious may have better recollection.
