### ISSUE TITLE
[BUG] The blind cannot stamp papers or put them together

### ISSUE THREAD

**Issue by Greenjoe12345** [Whitesands13/Whitesands#802]
## Round ID:
2716

## Reproduction:
So while a blind person cannot read papers, which makes sense, they also cannot stamp papers or clip to papers together, attempting to do so gives the message "As you are trying to read the (paper name), you suddenly feel very stupid!", even when you're just trying to do things that are not reading it, such as stamping or clipping papers together.

**Comment by TheRealScarHomie** [comment]
its because stamping opens the paper now, possible fix would be checking if someone is blind and if they are, randomly stamp on the paper
