### ISSUE TITLE
[BUG] Missing Sprite Megathread

### ISSUE THREAD

**Issue by untrius** [Whitesands13/Whitesands#828]
Please report anything that has a missing sprite or on-mob sprite in this thread.  I will need the exact name of the object, and including the path would be very helpful.  I will manually review the reported items and pass the information to the appropriate channels.  Once reviewed, I will react to your comment.  Thank you.

**Comment by Shadowtail117** [comment]
Wouldn't a discussion be better for a megathread like this?

**Comment by untrius** [comment]
Sure, works for me.
