### ISSUE TITLE
[BUG] OOC and mentorhelps laaaag behind

### ISSUE THREAD

**Issue by Shadowtail117** [Whitesands13/Whitesands#833]
Currently, there is a significant delay between sending an OOC message and it actually appearing in chat. The rest of the game is not affected; just sending OOC messages. Very very annoying.

*Happens to mentorhelps too.

## Testmerges:
N/A

## Reproduction:
Send any OOC message...and it takes 1000 years.

**Comment by Shadowtail117** [comment]
Happens to mentorhelps too.

**Comment by Shadowtail117** [comment]
This appears to have fixed itself.

**Comment by lunaboards-dev** [comment]
Yeah, this was related to the bot and server not being configured correctly.
