### ISSUE TITLE
[BUG] does sandbox work for you

### ISSUE THREAD

**Issue by WindowsErrors** [Whitesands13/Whitesands#844]
because it sure doesn't work for me

## Reproduction: set the game mode to sandbox and try looking for the sandbox panel

**Comment by untrius** [comment]
The verb is missing its category.  I'll get a PR in for this shortly.  The workaround is to type the verb "sandbox-panel" in the bar.

**Comment by WindowsErrors** [comment]
> The verb is missing its category. I'll get a PR in for this shortly. The workaround is to type the verb "sandbox-panel" in the bar.

before you go on i must tell you something

### sandbox is **HAUNTED**
and it hasn't been properly updated since like ~~2018~~ 2017

1. it's reliant on some sort of checker to allow **mobs** to use the sandbox panel (not player ckeys), so if you can even use the sandbox panel, but then you get race changed, mob changed, or otherwise polymorphed, you lose the ability to use it (same goes if your name changes)

2. because of this, you only get the option to open the sandbox panel if you spawn in at round start (if you can even use it at all), which means that if you late join or respawn, you won't be able to open and use it

3. [they removed sandbox](https://github.com/tgstation/tgstation/pull/58470), which should tell you as much as should be said about it, [au station](https://github.com/austation/austation/pull/2705) has some promising fixes but they kind of run on bee code so their sandbox code and our sandbox code are completely alien compared to each other

**Comment by untrius** [comment]
So what exactly are you asking for?  When it's sandbox mode, you want all non-ghost players to be able to use the sandbox panel?

**Comment by WindowsErrors** [comment]
don't really know what there is to say about sandbox mode, it's like extended except people get a little sandbox menu to spawn in whatever they want like the admin object spawn and then use it to make the engines and pipe constructs and give themselves revolvers and all the wizard spell books and one guy walks down the hallway spamming the Spawn Fuel Tank button and then batteryban ends the round because i spawned 30 crab 17 phones

**Comment by untrius** [comment]
It looks like Sandbox Mode has barely been maintained in the past 10 years.  I would argue that it needs a rewrite, but I can't say I have the time right now.

**Comment by Shadowtail117** [comment]
Seems like a wontfix situation then.
