### ISSUE TITLE
[BUG] the traitor calcium medipen starts out as spent

### ISSUE THREAD

**Issue by WindowsErrors** [Whitesands13/Whitesands#845]
## Round ID:
great sands round 52

## Testmerges:
potential issue sources
https://github.com/Whitesands13/Whitesands/pull/378
https://github.com/Whitesands13/Whitesands/pull/58

## Reproduction:
buy one from the bad guy market and it comes used

@MarkSuckerberg i'm laughing
no really, i am
![Screenshot (1428)](https://user-images.githubusercontent.com/58999300/117774328-37b6ed00-b1ee-11eb-9eb8-f4bf53711135.png)
~~i'm not actually laughing~~

**Comment by Shadowtail117** [comment]
@WindowsErrors please don't @ people in work items without good reason.
